revoke delete on table "public"."business_tokens" from "anon";

revoke insert on table "public"."business_tokens" from "anon";

revoke references on table "public"."business_tokens" from "anon";

revoke select on table "public"."business_tokens" from "anon";

revoke trigger on table "public"."business_tokens" from "anon";

revoke truncate on table "public"."business_tokens" from "anon";

revoke update on table "public"."business_tokens" from "anon";

revoke delete on table "public"."business_tokens" from "authenticated";

revoke insert on table "public"."business_tokens" from "authenticated";

revoke references on table "public"."business_tokens" from "authenticated";

revoke select on table "public"."business_tokens" from "authenticated";

revoke trigger on table "public"."business_tokens" from "authenticated";

revoke truncate on table "public"."business_tokens" from "authenticated";

revoke update on table "public"."business_tokens" from "authenticated";

revoke delete on table "public"."business_tokens" from "service_role";

revoke insert on table "public"."business_tokens" from "service_role";

revoke references on table "public"."business_tokens" from "service_role";

revoke select on table "public"."business_tokens" from "service_role";

revoke trigger on table "public"."business_tokens" from "service_role";

revoke truncate on table "public"."business_tokens" from "service_role";

revoke update on table "public"."business_tokens" from "service_role";

alter table "public"."business_tokens" drop constraint "business_tokens_business_id_fkey";

alter table "public"."business_tokens" drop constraint "business_tokens_pkey";

drop index if exists "public"."business_tokens_pkey";

drop table "public"."business_tokens";

create table "public"."business_location_job_payments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "business_id" uuid not null,
    "location_id" bigint not null,
    "job_id" bigint not null,
    "name" text not null,
    "type" text not null,
    "amount" double precision not null,
    "stripe_checkout_session_id" text
);


alter table "public"."business_location_job_payments" enable row level security;

CREATE UNIQUE INDEX business_location_job_payments_pkey ON public.business_location_job_payments USING btree (id);

alter table "public"."business_location_job_payments" add constraint "business_location_job_payments_pkey" PRIMARY KEY using index "business_location_job_payments_pkey";

alter table "public"."business_location_job_payments" add constraint "business_location_job_payments_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."business_location_job_payments" validate constraint "business_location_job_payments_business_id_fkey";

alter table "public"."business_location_job_payments" add constraint "business_location_job_payments_job_id_fkey" FOREIGN KEY (job_id) REFERENCES business_location_jobs(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."business_location_job_payments" validate constraint "business_location_job_payments_job_id_fkey";

alter table "public"."business_location_job_payments" add constraint "business_location_job_payments_location_id_fkey" FOREIGN KEY (location_id) REFERENCES business_locations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."business_location_job_payments" validate constraint "business_location_job_payments_location_id_fkey";

grant delete on table "public"."business_location_job_payments" to "anon";

grant insert on table "public"."business_location_job_payments" to "anon";

grant references on table "public"."business_location_job_payments" to "anon";

grant select on table "public"."business_location_job_payments" to "anon";

grant trigger on table "public"."business_location_job_payments" to "anon";

grant truncate on table "public"."business_location_job_payments" to "anon";

grant update on table "public"."business_location_job_payments" to "anon";

grant delete on table "public"."business_location_job_payments" to "authenticated";

grant insert on table "public"."business_location_job_payments" to "authenticated";

grant references on table "public"."business_location_job_payments" to "authenticated";

grant select on table "public"."business_location_job_payments" to "authenticated";

grant trigger on table "public"."business_location_job_payments" to "authenticated";

grant truncate on table "public"."business_location_job_payments" to "authenticated";

grant update on table "public"."business_location_job_payments" to "authenticated";

grant delete on table "public"."business_location_job_payments" to "service_role";

grant insert on table "public"."business_location_job_payments" to "service_role";

grant references on table "public"."business_location_job_payments" to "service_role";

grant select on table "public"."business_location_job_payments" to "service_role";

grant trigger on table "public"."business_location_job_payments" to "service_role";

grant truncate on table "public"."business_location_job_payments" to "service_role";

grant update on table "public"."business_location_job_payments" to "service_role";

create policy "Enable all actions for business admin"
on "public"."business_location_job_payments"
as permissive
for all
to authenticated
using (business_profile_has_role(business_id, 'admin'::text));


create policy "Enable all actions for business managers"
on "public"."business_location_job_payments"
as permissive
for all
to authenticated
using (business_profile_has_role(business_id, 'manager'::text));


create policy "Enable all actions for global admins"
on "public"."business_location_job_payments"
as permissive
for all
to authenticated
using (is_global_admin());


create policy "Enable all actions for job profiles"
on "public"."business_location_job_payments"
as permissive
for all
to authenticated
using (has_job_profile(job_id));


create policy "Enable all actions for location admin"
on "public"."business_location_job_payments"
as permissive
for all
to authenticated
using (location_profile_has_role(location_id, 'admin'::text));


create policy "Enable all actions for location manager"
on "public"."business_location_job_payments"
as permissive
for all
to authenticated
using (location_profile_has_role(location_id, 'manager'::text));



