create table "public"."business_location_channel_messages" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "channel_id" bigint not null,
    "profile_id" uuid not null,
    "message" text not null
);


alter table "public"."business_location_channel_messages" enable row level security;

create table "public"."business_location_channel_profiles" (
    "profile_id" uuid not null,
    "channel_id" bigint not null,
    "status" row_status not null default 'active'::row_status,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."business_location_channel_profiles" enable row level security;

create table "public"."business_location_channels" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "business_id" uuid not null,
    "location_id" bigint not null,
    "name" text not null,
    "status" row_status not null default 'active'::row_status
);


alter table "public"."business_location_channels" enable row level security;

CREATE UNIQUE INDEX business_location_channel_messages_pkey ON public.business_location_channel_messages USING btree (id);

CREATE UNIQUE INDEX business_location_channels_name_key ON public.business_location_channels USING btree (name);

CREATE UNIQUE INDEX business_location_channels_pkey ON public.business_location_channels USING btree (id);

alter table "public"."business_location_channel_messages" add constraint "business_location_channel_messages_pkey" PRIMARY KEY using index "business_location_channel_messages_pkey";

alter table "public"."business_location_channels" add constraint "business_location_channels_pkey" PRIMARY KEY using index "business_location_channels_pkey";

alter table "public"."business_location_channel_messages" add constraint "business_location_channel_messages_channel_id_fkey" FOREIGN KEY (channel_id) REFERENCES business_location_channels(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."business_location_channel_messages" validate constraint "business_location_channel_messages_channel_id_fkey";

alter table "public"."business_location_channel_messages" add constraint "business_location_channel_messages_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."business_location_channel_messages" validate constraint "business_location_channel_messages_profile_id_fkey";

alter table "public"."business_location_channel_profiles" add constraint "business_location_channel_profiles_channel_id_fkey" FOREIGN KEY (channel_id) REFERENCES business_location_channels(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."business_location_channel_profiles" validate constraint "business_location_channel_profiles_channel_id_fkey";

alter table "public"."business_location_channel_profiles" add constraint "business_location_channel_profiles_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."business_location_channel_profiles" validate constraint "business_location_channel_profiles_profile_id_fkey";

alter table "public"."business_location_channels" add constraint "business_location_channels_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."business_location_channels" validate constraint "business_location_channels_business_id_fkey";

alter table "public"."business_location_channels" add constraint "business_location_channels_location_id_fkey" FOREIGN KEY (location_id) REFERENCES business_locations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."business_location_channels" validate constraint "business_location_channels_location_id_fkey";

alter table "public"."business_location_channels" add constraint "business_location_channels_name_key" UNIQUE using index "business_location_channels_name_key";

grant delete on table "public"."business_location_channel_messages" to "anon";

grant insert on table "public"."business_location_channel_messages" to "anon";

grant references on table "public"."business_location_channel_messages" to "anon";

grant select on table "public"."business_location_channel_messages" to "anon";

grant trigger on table "public"."business_location_channel_messages" to "anon";

grant truncate on table "public"."business_location_channel_messages" to "anon";

grant update on table "public"."business_location_channel_messages" to "anon";

grant delete on table "public"."business_location_channel_messages" to "authenticated";

grant insert on table "public"."business_location_channel_messages" to "authenticated";

grant references on table "public"."business_location_channel_messages" to "authenticated";

grant select on table "public"."business_location_channel_messages" to "authenticated";

grant trigger on table "public"."business_location_channel_messages" to "authenticated";

grant truncate on table "public"."business_location_channel_messages" to "authenticated";

grant update on table "public"."business_location_channel_messages" to "authenticated";

grant delete on table "public"."business_location_channel_messages" to "service_role";

grant insert on table "public"."business_location_channel_messages" to "service_role";

grant references on table "public"."business_location_channel_messages" to "service_role";

grant select on table "public"."business_location_channel_messages" to "service_role";

grant trigger on table "public"."business_location_channel_messages" to "service_role";

grant truncate on table "public"."business_location_channel_messages" to "service_role";

grant update on table "public"."business_location_channel_messages" to "service_role";

grant delete on table "public"."business_location_channel_profiles" to "anon";

grant insert on table "public"."business_location_channel_profiles" to "anon";

grant references on table "public"."business_location_channel_profiles" to "anon";

grant select on table "public"."business_location_channel_profiles" to "anon";

grant trigger on table "public"."business_location_channel_profiles" to "anon";

grant truncate on table "public"."business_location_channel_profiles" to "anon";

grant update on table "public"."business_location_channel_profiles" to "anon";

grant delete on table "public"."business_location_channel_profiles" to "authenticated";

grant insert on table "public"."business_location_channel_profiles" to "authenticated";

grant references on table "public"."business_location_channel_profiles" to "authenticated";

grant select on table "public"."business_location_channel_profiles" to "authenticated";

grant trigger on table "public"."business_location_channel_profiles" to "authenticated";

grant truncate on table "public"."business_location_channel_profiles" to "authenticated";

grant update on table "public"."business_location_channel_profiles" to "authenticated";

grant delete on table "public"."business_location_channel_profiles" to "service_role";

grant insert on table "public"."business_location_channel_profiles" to "service_role";

grant references on table "public"."business_location_channel_profiles" to "service_role";

grant select on table "public"."business_location_channel_profiles" to "service_role";

grant trigger on table "public"."business_location_channel_profiles" to "service_role";

grant truncate on table "public"."business_location_channel_profiles" to "service_role";

grant update on table "public"."business_location_channel_profiles" to "service_role";

grant delete on table "public"."business_location_channels" to "anon";

grant insert on table "public"."business_location_channels" to "anon";

grant references on table "public"."business_location_channels" to "anon";

grant select on table "public"."business_location_channels" to "anon";

grant trigger on table "public"."business_location_channels" to "anon";

grant truncate on table "public"."business_location_channels" to "anon";

grant update on table "public"."business_location_channels" to "anon";

grant delete on table "public"."business_location_channels" to "authenticated";

grant insert on table "public"."business_location_channels" to "authenticated";

grant references on table "public"."business_location_channels" to "authenticated";

grant select on table "public"."business_location_channels" to "authenticated";

grant trigger on table "public"."business_location_channels" to "authenticated";

grant truncate on table "public"."business_location_channels" to "authenticated";

grant update on table "public"."business_location_channels" to "authenticated";

grant delete on table "public"."business_location_channels" to "service_role";

grant insert on table "public"."business_location_channels" to "service_role";

grant references on table "public"."business_location_channels" to "service_role";

grant select on table "public"."business_location_channels" to "service_role";

grant trigger on table "public"."business_location_channels" to "service_role";

grant truncate on table "public"."business_location_channels" to "service_role";

grant update on table "public"."business_location_channels" to "service_role";


